/** The order belongs to the oriented Fano presentation; semantic lookups use letters. */
export const BASIS = ['A', 'S', 'D', 'L', 'E', 'U', 'O'] as const;
export type Basis = (typeof BASIS)[number];
export type Complex = {re: number; im: number};
export type ReadoutSetting = 'real' | 'imaginary';

/** One-based cyclic triples: e_i e_j = e_k. */
export const FANO_LINES: readonly (readonly [number, number, number])[] = [
  [1, 2, 4], [2, 3, 5], [3, 4, 6], [4, 5, 7],
  [5, 6, 1], [6, 7, 2], [7, 1, 3],
];

/** Chosen diagonal Hamiltonian in illustrative, dimensionless time units. */
export const FREQUENCIES = [0, 0.19, 0.43, 0.71, 1.03, 1.39, 1.81] as const;
const INITIAL_PHASES = [0, 0.48, 1.11, 1.73, 2.64, 3.41, 4.55] as const;

/**
 * Γ(s,t) = (1−s) I₇/7 + s |ψ(t)⟩⟨ψ(t)|, ψⱼ = exp(i θⱼ)/√7.
 * θⱼ(t)=θⱼ(0)−ωⱼt gives the exact unitary orbit generated by diag(ωⱼ).
 * The slider chooses s; it is not a trajectory of the theory's nonlinear ODE.
 */
export function illustrativeState(strength: number, time = 0) {
  if (!Number.isFinite(strength) || strength < 0 || strength > 1 || !Number.isFinite(time)) {
    throw new RangeError('Expected 0 ≤ s ≤ 1 and finite time.');
  }
  const phases = INITIAL_PHASES.map((phase, j) => phase - FREQUENCIES[j] * time);
  const matrix: Complex[][] = phases.map((a, i) => phases.map((b, j) => {
    if (i === j) return {re: 1 / 7, im: 0};
    const magnitude = strength / 7;
    return {re: magnitude * Math.cos(a - b), im: magnitude * Math.sin(a - b)};
  }));
  const purity = (1 + 6 * strength * strength) / 7;
  return {
    matrix, phases, purity,
    integration: 6 * strength * strength,
    reflection: 1 / (1 + 6 * strength * strength),
    eigenvalues: [(1 + 6 * strength) / 7, ...Array<number>(6).fill((1 - strength) / 7)],
    inSelectedWindow: purity > 2 / 7 && purity <= 3 / 7,
  };
}

/**
 * Two three-outcome projective measurements on the fixed A,S subspace.
 * Re+: (|A⟩+|S⟩)/√2; Im+: (|A⟩−i|S⟩)/√2. The minus vector is
 * orthogonal to the plus vector, and the third effect is I−|A⟩⟨A|−|S⟩⟨S|.
 * Input is a density matrix in the declared BASIS. No reconstruction is assumed.
 */
export function pairReadout(matrix: readonly (readonly Complex[])[], setting: ReadoutSetting) {
  const population = matrix[0][0].re + matrix[1][1].re;
  const quadrature = setting === 'real' ? matrix[0][1].re : matrix[0][1].im;
  return {
    plus: population / 2 + quadrature,
    minus: population / 2 - quadrature,
    rest: matrix.reduce((sum, row, index) => index > 1 ? sum + row[index].re : sum, 0),
    quadrature,
  };
}
